services:
  - type: web
    name: final-ammar-db
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://ammar_database_user:xawbhp3RsPkcRcOUmrDF9aHmjy9hdGYg@dpg-d4e63hmr433s738gpe70-a/ammar_database"  # استبدل بالرابط الفعلي

# لا تضيف قسم databases
