services:
  - type: web
    name: ammar-name-storage
    env: python
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ammar-database
          property: connectionString

databases:
  - name: ammar-database
    plan: free
