services:
  - type: web
    name: ammar-name-storage
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ammar-database
          property: connectionString

databases:
  - name: ammar-database
    plan: free
    databaseName: ammar_storage
    user: ammar_user
