services:
  - type: web
    name: ammar-final-db
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ammar-database
          property: connectionString
